name: Run tests
on:
  pull_request:
  push: { branches: main }

jobs:
  run-test-suite:
    name: Run test suite
    runs-on: ubuntu-latest
    container: jjerphan/numba_dpex_dev:latest
      # TODO: setup runners with a compatible gpu and activate this option:
      # options: --device=/dev/dri  # enable gpu passthrough

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

      # TODO: replace development branch for engines in scikit learn with a fixed commit
      # commit when it's stable / remove this step when it's officially released
    - name: Install pytest, @ogrisel sklearn branch "wip-engines", and sklearn-numba-dpex
      run: pip install pytest git+https://github.com/ogrisel/scikit-learn.git@wip-engines#egg=scikit-learn -e .

    - name: Check device
      run: python -c "import dpctl; dpctl.select_default_device().print_device_info()"

    - name: Run sklearn_numba_dpex tests
      run: pytest sklearn_numba_dpex/

      # TODO: run those tests in a separate pipeline
    - name: Run sklearn test suites with sklearn_numba_dpex engines
      # TODO: test_kmeans_relocated_clusters on the sklearn side relies on the 
      # arbitrary tie-breaking behavior of the np.argpartition function. The 
      # within-partition order should be considered an implementation detail and 
      # sklearn_numba_depx own kernels for argpartition do not attempt to replicate the 
      # arbitrary tie breaking behavior of numpy and this causes this test to fail.
      # Maybe the test should be changed upstream so it doesn't have to rely on the 
      # within partition order in case of ties.
      # Until then this test is disabled but similar tests are internalized in
      # sklearn_numba_dpex.
      run: pytest --sklearn-engine-provider sklearn_numba_dpex --pyargs sklearn.cluster.tests.test_k_means -k "not test_kmeans_relocated_clusters"
