name: Run tests
on:
  pull_request:
  push: { branches: main }

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    container: jjerphan/numba_dpex_dev:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install sklearn-numba-dpex
      run: pip install -e . --no-build-isolation

    - name: Install pytest
      run: pip install pytest

    - name: Run tests
      run: |
        pip install pytest
        pytest sklearn_numba_dpex/
